# ********RoostGPT********

# Test generated by RoostGPT for test certain-integration using AI Type Open AI and AI Model gpt-4
# 
# ROOST_METHOD_HASH=b77f105368
# ROOST_METHOD_SIG_HASH=34456e7ede
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testDELETESession',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "Success"\n' +
#       'And the details are:\n' +
#       '    "Deleting session [R64EKX5RG32U]"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test

  Scenario: testDELETESession
    * url 'API_HOST_URL'
    Given path 'R64EKX5RG32U'
    When method delete
    Then status 200
    And match response == { message: '#string', status: 'Success' }
    And match response.path == 'R64EKX5RG32U'
    * print 'Deleting session [R64EKX5RG32U]'
