# ********RoostGPT********

# Test generated by RoostGPT for test certain-integration using AI Type Open AI and AI Model gpt-4
# 
# ROOST_METHOD_HASH=32e7aa68b7
# ROOST_METHOD_SIG_HASH=3596873209
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testAddLocation',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "Success"\n' +
#       'And the details are:\n' +
#       '    "Posting new location [UCLocation-HBER8FXU0J]"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test

  Background:
    * url API_HOST_URL
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario: Testing the addition of a new location
    Given path 'UCLocation-HBER8FXU0J'
    When method post
    Then status 200
    And match response.status == 'Success'
    And match response.details == 'Posting new location [UCLocation-HBER8FXU0J]'
