# ********RoostGPT********

# Test generated by RoostGPT for test certain-integration using AI Type Open AI and AI Model gpt-4
# 
# ROOST_METHOD_HASH=1e472e147b
# ROOST_METHOD_SIG_HASH=b33749b0e3
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testGETSessionInstanceView',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "Success"\n' +
#       'And the details are:\n' +
#       '    "Retrieving session instance view for event [testsimplesession]"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test

  Scenario: testGETSessionInstanceView
    * url API_HOST_URL
    And path API_ENDPOINT_ROUTE
    And configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }
    When method get
    Then status 200
    And match response.path == 'API_ENDPOINT_ROUTE'
    And match response == '#object'
    # Retrieving session instance view for event [testsimplesession]
    And match response.event == 'testsimplesession'
