# ********RoostGPT********

# Test generated by RoostGPT for test certain-integration using AI Type Open AI and AI Model gpt-4
# 
# ROOST_METHOD_HASH=fded7848df
# ROOST_METHOD_SIG_HASH=111959890f
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testGETSessionWithMultipleSearchFilters',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "404 Not Found"\n' +
#       'And the details are:\n' +
#       '    "No sessions found matching criteria"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test
  Description: This feature file includes all API tests.

  Background:
    * url API_HOST_URL
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario: Test GET Session With Multiple Search Filters
    Description: This scenario tests the GET session with multiple search filters.

    Given path API_ENDPOINT_ROUTE
    When method get
    Then status 404
    And match response == { message: 'No sessions found matching criteria' }
