# ********RoostGPT********

# Test generated by RoostGPT for test certain-integration using AI Type Open AI and AI Model gpt-4
# 
# ROOST_METHOD_HASH=714c4daaf4
# ROOST_METHOD_SIG_HASH=b2948c3472
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testFetchNonExistentSession',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "404 Not Found"\n' +
#       'And the details are:\n' +
#       '    "Session with ID R64EKX5RG32U not found"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test
  Description: This feature file includes all API tests

  Background:
    * url API_HOST_URL
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario: Fetch Non-Existent Session
    Description: This scenario tests the fetch operation for a non-existent session

    Given path 'R64EKX5RG32U'
    When method get
    Then status 404
    And match response == { message: 'Session with ID R64EKX5RG32U not found' }
