# ********RoostGPT********

# Test generated by RoostGPT for test certain-integration using AI Type Open AI and AI Model gpt-4
# 
# ROOST_METHOD_HASH=50ec353220
# ROOST_METHOD_SIG_HASH=22e1a8dc21
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testUpdateLocationCapacity',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "Success"\n' +
#       'And the details are:\n' +
#       '    "Updating capacity for location UCLocation-HBER8FXU0J to 20"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test
  Description: This feature file tests all the APIs

  Background:
    * url 'API_HOST_URL'
    * configure headers = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }

  Scenario: Update Location Capacity
    Description: This scenario tests the update location capacity API

    Given path 'UCLocation-HBER8FXU0J'
    And request { capacity: 20 }
    When method put
    Then status 200
    And match response == { result: 'Success' }
    And match response.details == 'Updating capacity for location UCLocation-HBER8FXU0J to 20'
